encyclopedia/urls.py
from django.urls import path
from . import views
app_name="pages"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.wiki, name="wikipage"),
    path("Error/<str:error>", views.error, name="error")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponse
from markdown import markdown
from . import util
import random
class SearchEntryForm(forms.Form):
    entry_search = forms.CharField(
        label="",       
        widget=forms.TextInput(attrs={'placeholder': 'Cauta problema...    ', 'class': 'search-input'})
    )

def index(request):
    entries_ = util.list_entries()
    entry_search = None
    search_list = []
    random_page=random.choice(entries_)
    print(random_page)
    if request.method == "POST":
        form_index = SearchEntryForm(request.POST)
        if form_index.is_valid():
            entry_search = form_index.cleaned_data["entry_search"]
            if entry_search:
                search_list = [entry for entry in entries_ if entry_search.lower() in entry.lower()]
            for entry in entries_:
                    if entry_search.lower() == entry.lower():
                        return redirect('pages:wikipage', entry=entry)
            if len(search_list)==0:
                return redirect('pages:error', error=f'No search results for "{entry_search}"')
    return render(request, "encyclopedia/index.html", {
        "entries": entries_,
        "form": SearchEntryForm(),
        "entry_search": entry_search,
        "search_list" : search_list,
        "random_page" : random_page,
    })


def wiki(request, entry):
    #layout var:
    entries_ = util.list_entries()
    entry_search = None
    search_list = []
    random_page=random.choice(entries_)
    print(random_page)
    if request.method == "POST":
        form_index = SearchEntryForm(request.POST)
        if form_index.is_valid():
            entry_search = form_index.cleaned_data["entry_search"]
            if entry_search:
                search_list = [entry for entry in entries_ if entry_search.lower() in entry.lower()]
            for entry in entries_:
                    if entry_search.lower() == entry.lower():
                        return redirect('pages:wikipage', entry=entry)
            if len(search_list)==0:
                return redirect('pages:error', error=f'No search results for "{entry_search}"')
    #done layout
    if entry not in entries_:
         return redirect('pages:error', error="Page could not be found")
    coded_text=util.get_entry(entry)
    print(coded_text[0])
    link = coded_text[0]
    if isinstance(link, bytes):  # Check if it's a bytes object
        link = link.decode("utf-8")  # Decode it to a string
    if coded_text is None:
        return HttpResponse("The requested page was not found.", status=404)
    content=markdown(coded_text[1])
    return render(request, "encyclopedia/wikipage.html", {
        "entry" : entry,
        "link" : link,
        "content" :content,
        "entries": entries_,
        "form": SearchEntryForm(),
        "entry_search": entry_search,
        "search_list" : search_list,
        "random_page" : random_page,
    })


def error(request, error="Page could not be found"):
    #layout var:
    entries_ = util.list_entries()
    entry_search = None
    search_list = []
    random_page=random.choice(entries_)
    print(random_page)
    if request.method == "POST":
        form_index = SearchEntryForm(request.POST)
        if form_index.is_valid():
            entry_search = form_index.cleaned_data["entry_search"]
            if entry_search:
                search_list = [entry for entry in entries_ if entry_search.lower() in entry.lower()]
            for entry in entries_:
                    if entry_search.lower() == entry.lower():
                        return redirect('pages:wikipage', entry=entry)
            if len(search_list)==0:
                return redirect('pages:error', error=f'No search results for "{entry_search}"')
    #done layout
     
    return render(request, "encyclopedia/error.html", {
        "error" : error,
        "entries": entries_,
        "form": SearchEntryForm(),
        "entry_search": entry_search,
        "search_list" : search_list,
        "random_page" : random_page,
     })

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
Error Alert
{% endblock %}

{% block body %}
<div class="error-div">
    <div class="error-header">
        <h1>Error :(</h1>
    </div>
    <div class="error-message">
        <h1>{{error}}!</h1>
    </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div class="index-cont">
        <h1 class="mod-txt" style="margin-left: 5%;">Probleme</h1>
        <hr>
        <ul class="list">
            {% if entry_search %}
                {% for entry in search_list %}
                    <li class="list-item"><a class="pg-link" href="{% url 'pages:wikipage' entry=entry %}">{{ entry }}</a></li>
                {% endfor %}
            {% else %}
                {% for entry in entries %}
                    <li class="list-item"><a class="pg-link" href="{% url 'pages:wikipage' entry=entry %}">{{ entry }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                {% block nav %}
                {% endblock %}
                <h2 class="main-header">Backtracking</h2>
                <hr style="opacity: 0;">
                <form action="{% url 'pages:index' %}" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                </form>
                <div class="main-cont">
                <div class="ftr-cont">
                    <a href="{% url 'pages:index' %}" class="feature_link">Acasa</a>
                </div>
                <div class="ftr-cont">
                    <a href="{% url 'pages:wikipage' entry=random_page %}" class="feature_link">Problema Aleatorie</a>
                </div>
            </div>
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/wikipage.html
{% extends "encyclopedia/layout.html" %}
{% block title %}{{entry}}{% endblock %}
    {% block body %}
        <hr>
    <iframe
 frameBorder="0"
 height="450px"
 src="{{link|safe}}" 
 width="100%"
 ></iframe>
 <hr>
 <div class="space" style="height: 60px;"></div>
 {{ content|safe }}
        

    {% endblock %}